# Generated by Django 5.0.7 on 2024-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_nid', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_nid', models.CharField(blank=True, max_length=50, null=True)),
                ('present_division', models.CharField(blank=True, max_length=100, null=True)),
                ('present_district', models.CharField(blank=True, max_length=100, null=True)),
                ('present_upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_division', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
