# Generated by Django 5.0.7 on 2024-11-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_admin_applicant_babyreg_district_division_healthcare_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
